<docs>
	<doc for="RemotingException.RemotingException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.RemotingException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.RemotingException"/> class with default
   properties.</para>
		</summary>
		<remarks>
			<para><see cref="System.Runtime.Remoting.RemotingException"/> inherits from the <see cref="System.SystemException"/> class. The following table 
   shows initial property values for an instance of the <see cref="System.Runtime.Remoting.RemotingException"/>
   class:</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The empty string
   ("").</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
	</doc><doc for="ServerException.ServerException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.ServerException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.ServerException"/> class with default properties.</para>
		</summary>
		<remarks>
			<para><see cref="System.Runtime.Remoting.ServerException"/> inherits from the <see cref="System.SystemException"/> class. The following table shows initial property values 
   for an instance of the <see cref="System.Runtime.Remoting.ServerException"/>
   class:</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The empty string ("").</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
	</doc><doc for="ServerException.ServerException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.ServerException"/> class with a specified message.</para>
		</summary>
		<param name="message">The message that describes the exception</param>
		<remarks>
			<para><see cref="System.Runtime.Remoting.ServerException"/> inherits from the <see cref="System.SystemException"/> class. The following table shows initial property values 
   for an instance of the <see cref="System.Runtime.Remoting.ServerException"/> class:</para>
			<list type="table"><listheader>
					<term>Property Type</term>
					<description>Condition</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/> .</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The <paramref name="message "/>string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
	</doc><doc for="ServerException.ServerException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.ServerException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="InnerException">The exception that is the cause of the current exception. If the <paramref name="InnerException"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows initial property values for an 
   instance of the <see cref="System.Runtime.Remoting.ServerException"/> class:</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="RemotingTimeoutException.RemotingTimeoutException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.RemotingTimeoutException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.RemotingTimeoutException"/> class with default properties.</para>
		</summary>
		<remarks>
			<para><see cref="System.Runtime.Remoting.RemotingTimeoutException"/> inherits from the <see cref="System.Exception"/> class. The following table 
   shows initial property values for an instance of the <see cref="System.Runtime.Remoting.RemotingTimeoutException"/>
   class:</para>
			<list type="table">
				<listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>Localized error message for <see cref="System.Runtime.Remoting.RemotingTimeoutException"/>.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="RemotingTimeoutException.RemotingTimeoutException1">
		<summary>
			<para>Initializes a new instance of <see cref="System.Runtime.Remoting.RemotingTimeoutException"/> class with a specified message.</para>
		</summary>
		<param name="message">The message that indicates the reason why the exception occurred.</param>
		<remarks>
			<para><see cref="System.Runtime.Remoting.RemotingTimeoutException"/> inherits from the <see cref="System.Exception"/> class. The following table 
   shows initial property values for an instance of the <see cref="System.Runtime.Remoting.RemotingTimeoutException"/>
   
   class:</para>
			<list type="table">
				<listheader>
					<term>Property Type</term>
					<description>Condition</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/>.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The <paramref name="message"/> string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="RemotingException.RemotingException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.RemotingException"/> class with a specified
   message.</para>
		</summary>
		<param name="message"> The error message that explains why the exception occurred.</param>
		<remarks>
			<para><see cref="System.Runtime.Remoting.RemotingException"/> inherits from the <see cref="System.SystemException"/> class. The following table 
   shows initial property values for an instance of the <see cref="System.Runtime.Remoting.RemotingException"/>
   class:</para>
			<list type="table"><listheader>
					<term>Property Type</term>
					<description>Condition</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/> .</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The <paramref name="message
   "/>string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
	</doc><doc for="RemotingException.RemotingException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.RemotingException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains why the exception occurred.</param>
		<param name="InnerException">The exception that is the cause of the current exception. If the <paramref name="InnerException"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception will include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows initial property values for an 
   instance of the <see cref="System.Runtime.Remoting.RemotingException"/> class:</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="RemotingException.RemotingException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.RemotingException"/> class from serialized data.</para>
		</summary>
		<param name="info"><para> The object that holds the serialized object data.</para></param>
		<param name="context">The contextual information about the source or destination of the exception.</param>
		<exception cref="System.ArgumentNullException">The <paramref name="info"/> parameter is <see langword="null"/>.</exception>
		<remarks>
			<para>This constructor is called during deserialization to
      reconstitute the exception object transmitted over a stream. (For more
      information on serialization, see <see topic="cpconSerialization"/>.)</para>
		</remarks>
	</doc><doc for="RemotingTimeoutException.RemotingTimeoutException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Runtime.Remoting.RemotingTimeoutException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="InnerException">The exception that is the cause of the current exception. If the <paramref name="InnerException"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception must include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows initial property values for an
   instance of the <see cref="System.Runtime.Remoting.RemotingTimeoutException"/> class:</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="RemotingException">
		<summary>
			<para>The exception that is thrown when something has gone wrong during
      remoting.</para>
		</summary>
		<remarks>
			<para><see cref="System.Runtime.Remoting.RemotingException"/> uses the HRESULT COR_E_REMOTING, which has the value
   0x8013150B.</para>
			<para><see cref="System.Runtime.Remoting.RemotingException"/> uses the default <see cref="System.Object.Equals"/> implementation, which supports
reference equality.</para>
			<para>For a list of initial property values for an instance of <see cref="System.Runtime.Remoting.RemotingException"/>, see
the <see cref="System.Runtime.Remoting.RemotingException"/> constructors.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="ServerException">
		<summary>
			<para> The exception that is thrown to communicate errors to the client when the client connects
      to non .NET Framework applications that cannot throw exceptions.</para>
		</summary>
		<remarks>
			<para><see cref="System.Runtime.Remoting.ServerException"/> uses the HRESULT COR_E_SERVER, which has the value 0x8013150E.</para>
			<para><see cref="System.Runtime.Remoting.ServerException"/> uses the default <see cref="System.Object.Equals"/> implementation, which supports reference equality.</para>
			<para>For a list of initial property values for an instance of <see cref="System.Runtime.Remoting.ServerException"/>, see the
<see cref="System.Runtime.Remoting.ServerException"/> constructors.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
		<seealso cref="System.Exception"/>
	</doc><doc for="RemotingTimeoutException">
		<summary>
			<para>The exception that is thrown when the server or the client cannot
      be reached for a previously specified period of time.</para>
		</summary>
		<remarks>
			<para>The <see cref="System.Runtime.Remoting.RemotingTimeoutException"/> is thrown when a remoting call does not
   complete in the specified timeout time.</para>
			<para><see cref="System.Runtime.Remoting.RemotingTimeoutException"/> uses the HRESULT COR_E_REMOTING, which
has the value 0x8013150B.</para>
			<para><see cref="System.Runtime.Remoting.RemotingTimeoutException"/> uses the default <see cref="System.Object.Equals"/>
implementation, which supports reference equality.</para>
			<para>For a list of initial property values for an instance of <see cref="System.Runtime.Remoting.RemotingTimeoutException"/>, see the
<see cref="System.Runtime.Remoting.RemotingTimeoutException"/>
constructors.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc></docs>
