<docs>
	<doc for="TargetException.TargetException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetException"/> class
   with an empty message and the
   root cause of the exception.</para>
		</summary>
		<remarks>
			<para>The <see langword="InnerException"/> property is set 
   to <see langword="null"/>
   and the HRESULT error code is set to COR_E_TARGET.</para>
			<para><see langword="TargetException"/> inherits from the <see cref="System.Exception"/>. This constructor sets the 
properties of the <see langword="Exception"/>
object as shown in
the following table.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/></description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The empty string ("").</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="TargetException.TargetException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetException"/>
class with the given message
and the root cause exception.</para>
		</summary>
		<param name="message">A <see langword="String"/> describing the reason why the exception occurred.</param>
		<remarks>
			<para><see langword="TargetException"/> inherits from the <see cref="System.Exception"/>. This constructor sets the 
   properties of the <see langword="Exception"/>
   object as shown in
   the following table.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description><see langword="null"/></description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The message string.</description>
				</item>
			</list>
		</remarks>
	</doc><doc for="TargetException.TargetException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetException"/> class with the specified
   serialization and context information.</para>
		</summary>
		<param name="info">The data for serializing or deserializing the object.</param>
		<param name=" context">The source of and destination for the object.</param>
	</doc><doc for="TargetException">
		<summary>
			<para> Represents the exception that is thrown when an attempt is made to
      invoke an invalid target.
      </para>
		</summary>
		<remarks>
			<para>A <see langword="TargetException"/> is thrown when an attempt is made to invoke a non-static method on a null
   object. This may occur because the
   caller does not have access to the member, or because the target does not
   define the member, and so on.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="TargetException.TargetException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Reflection.TargetException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc></docs>
