<docs>
	<doc for="TargetInvocationException">
		<summary>
			<para>The exception that is thrown by methods invoked through reflection. This class cannot
      be inherited.</para>
		</summary>
		<remarks>
			<para><see langword="TargetInvocationException"/> uses the HRESULT COR_E_TARGETINVOCATION which has
   the value 0x80131604.</para>
			<para>When created, the
<see langword="TargetInvocationException"/> is passed a reference to the
   exception thrown by the method invoked through reflection. The <see cref="System.Exception.InnerException"/>
   property holds the underlying exception.</para>
		</remarks>
		<seealso cref="System.Exception.InnerException"/>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="TargetInvocationException.TargetInvocationException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetInvocationException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Reflection.TargetInvocationException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="TargetInvocationException.TargetInvocationException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetInvocationException"/> class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.Reflection.TargetInvocationException"/>
class with a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="inner">The exception that is the cause of the current exception. If the <paramref name="inner"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Reflection.TargetInvocationException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc></docs>
