<docs>
	<doc for="VerificationException.VerificationException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Security.VerificationException"/> class
    with an explanatory message.</para>
		</summary>
		<param name="message">A message indicating the reason the exception occurred.</param>
	</doc>
	<doc for="VerificationException.VerificationException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Security.VerificationException"/> class with serialized data.</para>
		</summary>
		<param name="info">The object that holds the serialized object data.</param>
		<param name=" context">The contextual information about the source or destination.</param>
		<remarks>
			<para>This constructor is called during deserialization to 
      reconstitute the exception object transmitted over a stream. For more
      information, see <see topic="cpconserialization"/>.</para>
		</remarks>
	</doc><doc for="VerificationException.VerificationException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.Security.VerificationException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="innerException">The exception that is the cause of the current exception. If the <paramref name="innerException"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.Security.VerificationException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="VerificationException">
		<summary>
			<para> The exception that is thrown when the security policy requires code to be type safe and the verification process is unable to verify that the code
      is type safe.</para>
		</summary>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
	</doc><doc for="VerificationException.VerificationException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.Security.VerificationException"/>
class.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.Security.VerificationException"/>
class with default properties.</para>
		</summary>
		<remarks>
			<para><see cref="System.Security.VerificationException"/> uses the HRESULT COR_E_VERIFICATION.</para>
		</remarks>
	</doc>
</docs>
