<docs>
	<doc for="DirectoryNotFoundException">
		<summary>
			<para> The exception that is thrown when part of a file or directory
      cannot be found.</para>
		</summary>
		<remarks>
			<para><see langword="DirectoryNotFoundException"/> uses the HRESULT
   COR_E_DIRECTORYNOTFOUND which has the value 0x80070003. Note that
<see langword="DirectoryNotFoundException"/> is also thrown when COM 
   interop programs see the HRESULT STG_E_PATHNOTFOUND, which has the value
   0x80030003.</para>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="DirectoryNotFoundException.DirectoryNotFoundException">
		<overload>
			<para>Initializes a new instance of the <see cref="System.IO.DirectoryNotFoundException"/> class with its message
   string.</para>
		</overload>
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.DirectoryNotFoundException"/> class with
   its message string set to a system-supplied message and its HRESULT set to
   COR_E_DIRECTORYNOTFOUND.</para>
		</summary>
		<remarks>
			<para>This constructor initializes the <see cref="System.Exception.Message" qualify="true"/> property of the new instance to a
   system-supplied message that describes the error, such as "Could not find the
   specified directory." This message takes into account the current system
   culture. </para>
			<para>The <see cref="System.Exception.InnerException" qualify="true"/> property of the new instance is initialized to
<see langword="null"/>. </para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="DirectoryNotFoundException.DirectoryNotFoundException1">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.DirectoryNotFoundException"/> class with its message string set to <paramref name="message"/> and its HRESULT set to COR_E_DIRECTORYNOTFOUND.</para>
		</summary>
		<param name="message">A <see cref="System.String"/> that describes the error. The content of <paramref name="message"/> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</param>
		<remarks>
			<para>This constructor initializes the <see cref="System.Exception.Message" qualify="true"/> property of the new instance using
<paramref name="message"/> . </para>
			<para>The <see cref="System.Exception.InnerException" qualify="true"/> property of the new instance is initialized to <see langword="null"/>. </para>
		</remarks>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="DirectoryNotFoundException.DirectoryNotFoundException2">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.DirectoryNotFoundException"/>
class with a specified error message and a reference to the
inner exception that is the cause of this exception.</para>
		</summary>
		<param name="message">The error message that explains the reason for the exception.</param>
		<param name="innerException">The exception that is the cause of the current exception. If the <paramref name="innerException"/> parameter is not <see langword="null"/>, the current exception is raised in a <see langword="catch"/> block that handles the inner exception.</param>
		<remarks>
			<para>An exception that is thrown as a direct result of a
      previous exception should include a reference to the previous exception in
      the <see cref="System.Exception.InnerException"/> property. The
   <see cref="System.Exception.InnerException"/>
   property returns the same value that is passed into the constructor, or
<see langword="null"/> if the <see cref="System.Exception.InnerException"/> 
property does not supply the inner exception value to
the constructor. </para>
			<para>The following table shows the initial property values for an instance of <see cref="System.IO.DirectoryNotFoundException"/>.</para>
			<list type="table"><listheader>
					<term>Property</term>
					<description>Value</description>
				</listheader>
				<item>
					<term><see cref="System.Exception.InnerException"/></term>
					<description>The inner exception reference.</description>
				</item>
				<item>
					<term><see cref="System.Exception.Message"/></term>
					<description>The error message string.</description>
				</item>
			</list>
		</remarks>
		<seealso cref="System.Exception"/>
		<seealso topic="cpconHandlingThrowingExceptions"/>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
	<doc for="DirectoryNotFoundException.DirectoryNotFoundException3">
		<summary>
			<para>Initializes a new instance of the <see cref="System.IO.DirectoryNotFoundException"/> class with the specified serialization and context information.</para>
		</summary>
		<param name="info">The <see cref="System.Runtime.Serialization.SerializationInfo"/> that holds the serialized object data about the exception being thrown.</param>
		<param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> that contains contextual information about the source or destination.</param>
		<seealso topic="cpconworkingwithio"/>
		<seealso topic="cpconreadingtextfromfile"/>
		<seealso topic="cpconwritingtexttofile"/>
	</doc>
</docs>
